services:
  - type: web
    name: maillots-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build && npx prisma db push --accept-data-loss
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
